#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros -Q -- $0 "$@"
|#

(ql:quickload :quickdocs-updater :silent t)

(defun main (&optional (ql-dist-version (ql-dist:version (ql-dist:dist "quicklisp"))))
  (quickdocs-updater:update-dist ql-dist-version))
