#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros -Q -- $0 "$@"
|#

(ql:quickload '(:datafly :quickdocs-updater) :silent t)

(defun main (&optional (ql-dist-version (ql-dist:version (ql-dist:dist "quicklisp"))))
  (datafly:connect-toplevel :mysql :database-name "quickdocs"
                            :username "root")
  (let ((sb-impl::*default-external-format* :utf-8)
        (sb-alien::*default-c-string-external-format* :utf-8))
    (quickdocs-updater:update-cliki-info ql-dist-version)))
